services:
  database:
    container_name: snote-database
    image: postgres:latest
    restart: on-failure:5
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - database:/var/lib/postgresql
    networks:
      - internal
  dbx:
    container_name: snote-dbx
    image: t8y2/dbx
    restart: on-failure:5
    volumes:
      - dbx:/app/data
    networks:
      - internal

  api:
    container_name: snote-api
    environment:
      DATABASE_URL: postgres://${PG_USER}:${PG_PASS}@database/${PG_DB}

      ORIGINS: ${ORIGINS}

      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_SECRET}

      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUCKET: ${S3_BUCKET}

      ASSEMBLY_AI_API_KEY: ${ASSEMBLY_AI_API_KEY}
    image: ${REGISTRY}/api:latest
    restart: always
    depends_on:
      - database
    networks:
      - internal

  cloudflare-tunnel:
    container_name: snote-cloudflare
    image: cloudflare/cloudflared
    restart: on-failure:5
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - internal

networks:
  internal:
    name: snote-network
    external: true

volumes:
  database:
    name: snote-database
    external: true
  dbx:
    name: snote-dbx
    external: true
