on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io/snote-startup/snote

      PG_USER: ${{ secrets.PG_USER }}
      PG_PASS: ${{ secrets.PG_PASS }}
      PG_DB: ${{ secrets.PG_DB }}

      API_URL: ${{ secrets.API_URL }}

      ORIGINS: ${{ secrets.ORIGINS }}

      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}

      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}

      PAYMENT_REDIRECT_URL: ${{ secrets.PAYMENT_REDIRECT_URL }}
      PAYOS_CLIENT_ID: ${{ secrets.PAYOS_CLIENT_ID }}
      PAYOS_API_KEY: ${{ secrets.PAYOS_API_KEY }}
      PAYOS_CHECKSUM_KEY: ${{ secrets.PAYOS_CHECKSUM_KEY }}

      ASSEMBLY_AI_API_KEY: ${{ secrets.ASSEMBLY_AI_API_KEY }}

      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      CHAT_CONTEXT_HISTORY_SIZE: ${{ secrets.CHAT_CONTEXT_HISTORY_SIZE }}
      CHAT_CONTEXT_TRANSCRIPT_SIZE: ${{ secrets.CHAT_CONTEXT_TRANSCRIPT_SIZE }}

      CLOUDFLARE_TUNNEL_TOKEN: ${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}
    steps:
      - name: Checkout Develop
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Clean Container, Image And Prepare For Deploy
        run: docker compose -f compose.yaml -p snote down --rmi all -v
      - name: Deploy Application
        run: docker compose -f compose.yaml -p snote up -d
